export const ENDPOINTS = {
  auth: {
    login: '/auth/login',
    signup: '/auth/signup',
    me: '/auth/me',
    forgotPassword: '/auth/forgot-password',
    resetPassword: '/auth/reset-password',
    changePassword: '/auth/change-password',
    refreshToken: '/auth/refresh-token',
    logout: '/auth/logout',
  },
  dashboard: '/dashboard',
  vendors: '/vendors',
  vendorSearch: '/vendors/search',
  vendor: (id: string) => `/vendors/${id}`,
  rfqs: '/rfqs',
  rfq: (id: string) => `/rfqs/${id}`,
  rfqVendors: (id: string) => `/rfqs/${id}/vendors`,
  rfqAttachments: (id: string) => `/rfqs/${id}/attachments`,
  rfqClose: (id: string) => `/rfqs/${id}/close`,
  quotations: '/quotations',
  quotationsVendor: '/quotations/vendor',
  quotationsByRfq: (rfqId: string) => `/quotations/rfq/${rfqId}`,
  quotation: (id: string) => `/quotations/${id}`,
  quotationWithdraw: (id: string) => `/quotations/${id}/withdraw`,
  comparisons: (rfqId: string) => `/comparisons/${rfqId}`,
  approvals: '/approvals',
  approvalTimeline: (id: string) => `/approvals/${id}/timeline`,
  approvalApprove: (id: string) => `/approvals/${id}/approve`,
  approvalReject: (id: string) => `/approvals/${id}/reject`,
  purchaseOrders: '/purchase-orders',
  purchaseOrder: (id: string) => `/purchase-orders/${id}`,
  purchaseOrderPdf: (id: string) => `/purchase-orders/${id}/pdf`,
  purchaseOrderEmail: (id: string) => `/purchase-orders/${id}/email`,
  invoices: '/invoices',
  invoice: (id: string) => `/invoices/${id}`,
  invoicePdf: (id: string) => `/invoices/${id}/pdf`,
  invoiceEmail: (id: string) => `/invoices/${id}/email`,
  invoicePaid: (id: string) => `/invoices/${id}/paid`,
  notifications: '/notifications',
  notificationsReadAll: '/notifications/read-all',
  notificationRead: (id: string) => `/notifications/${id}/read`,
  logs: '/logs',
  reports: {
    vendorPerformance: '/reports/vendor-performance',
    procurementSummary: '/reports/procurement-summary',
    monthlyTrends: '/reports/monthly-trends',
    spendAnalysis: '/reports/spend-analysis',
    export: '/reports/export',
  },
} as const;
